apiVersion: v1
kind: Pod
metadata:
  name: combine
  labels:
    app: qos
spec:
  containers:
  - name: p-gen
    image: sheng3310/ping
  - name: qos-monitor
    image: sheng3310/qos-monitor
    ports:
    - name: http
      containerPort: 80
    imagePullPolicy: Always
    livenessProbe:
      httpGet:
        path: /alive
        port: 80
      initialDelaySeconds: 20
